import Head from 'next/head'
import React from 'react'
import Footer from './footer/footer'
import Header from './header/header'
import styles from './layout.module.scss'

const  Layout = ({ children, header, footer, mainDir }) => {
  //console.log(header, footer);
  return (
    <div className="body">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {header == 'hide' ? '' : (
        <Header />
      )}

      <main className={`main max-w-full overflow-hidden ${mainDir == 'ltr' ? styles.dirLtr : styles.dirRtl}`} >
        { children }
      </main>

      {footer == 'hide' ? '' : (
        <Footer />
      )}
    </div>
  )
}

export default Layout