import Head from 'next/head'
import React from 'react'
import Footer from './footer/footer'
import Header from './header/header'

const  Layout = ({ children }) => {
  return (
    <div className="body">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <main className="main">
        { children }
      </main>

      <Footer />
    </div>
  )
}

export default Layout