import Head from 'next/head'

export default function Index() {
  return (
    <div className="body">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        
      </main>
    </div>
  )
}
